### PR TITLE
attempt basic error handling from native code

### PR DESCRIPTION
**Pull request by cryptodeal**
Attempts to add a basic implementation of native error handling that works hand in hand w TS Error handling. It has room for improvement in terms of additional functionality, but I think this is a good first step at hashing out a native code error handling API RE #26.

### CODE REVIEW

**Comment by cryptodeal** [comment]
I disabled the 2 failing tests so we can get clean CI runs to help signal what is/isn't ready to be merged haha, but this works quite nicely to provide insight into each of the failing unit tests I've re-enabled locally (although disabled in commit ^^).

Screenshots of CLI output for each of the currently commented out/otherwise disabled unit tests (bear in mind, 50% were disabled as ArrayFire only supports Tensors with up to, and including, 4 Dims; the other 50% are `conv` or `conv2dBackward` tests, which are also not yet fully implemented):

Screen Shot 2022-10-06 at 9 37 42 PM

And the actual CLI output for each error:
Screen Shot 2022-10-06 at 9 39 20 PM

Screen Shot 2022-10-06 at 9 39 41 PM

Screen Shot 2022-10-06 at 9 40 03 PM

Screen Shot 2022-10-06 at 9 40 17 PM

Screen Shot 2022-10-06 at 9 40 31 PM

Screen Shot 2022-10-06 at 9 42 06 PM

Screen Shot 2022-10-06 at 9 42 52 PM

Screen Shot 2022-10-06 at 9 43 13 PM

Screen Shot 2022-10-06 at 9 43 36 PM

Screen Shot 2022-10-06 at 9 43 59 PM

**Comment by cryptodeal** [comment]
Last push simply removes a few `/* TODO: Fix failing test */` comments throughout the unit tests where we have since fixed the failing tests. 💯

**Comment by cryptodeal** [comment]
Out of all the functions in `flashlight_binding.cc`, I've so far only wrapped `_conv2dBackwardData` in a try/catch, calling `handleError` there, but not in any of the other functions; we'll probably want to do so, but I'll wait for feedback (including potentially which functions should be wrapped).

**Comment by cryptodeal** [comment]
Formatting of errors after final tweaks (to mirror the style Bun uses to log errors):
PRETTY_EXCEPTION

**Review by bwasti — COMMENTED** [review]
this is really elegant!  does bun wiptest have a way to expect exceptions?

**Comment by cryptodeal** [comment]
> this is really elegant! does bun wiptest have a way to expect exceptions?

I am not sure, but will dig into this!

**Pull request merged**
