### PR TITLE
add tensor class methods convert to varying TypedArrays

### PR DESCRIPTION
**Pull request by cryptodeal**
Add native code Functions:

1. `_float16Buffer`
2. `_float32Buffer`
3. `_float64Buffer`
4. `_bool8Buffer`
5. `_int16Buffer`
6. `_int32Buffer`
7. `_int64Buffer`
8. `_uint8Buffer`
9. `_uint16Buffer`
10. `_uint32Buffer`
11. `_uint64Buffer`

Additionally, update `ffi_tensor.ts` schema accordingly as well as implement tensor class methods wrapping the native functions.

Testing `toBool8Buffer` in unit tests for `lessThan`, `greaterThan`, `lessThanEqual`, and `greaterThanEqual`.

### CODE REVIEW

**Comment by cryptodeal** [comment]
I've left `toFloat16Array` code in tensor method, but have commented out and linked to #54  in the comment for clarity.

**Comment by cryptodeal** [comment]
Per feedback from @jacobkahn on Discord, removed `_bool8Buffer` and tensor class methods until flashlight has implemented bool specialization for host.

**Review by bwasti — APPROVED** [review]
woo! thanks for adding this :)

**Comment by cryptodeal** [comment]
> woo! thanks for adding this :)

No problem; will start working on the 2nd PR RE tensor data types today as well!

**Pull request merged**
