### PR TITLE
Implement `dispose`

### PR DESCRIPTION
**Pull request by cryptodeal**
Bun appears to run GC twice; if you uncomment the logged output in `destroyTensor` (only called @ Garbage Collection), the output is logged multiple times per pointer).

This causes the test to segfault as first GC, bun finds the pointer in `alreadyDestroyed` & removes the pointer from the set. 2nd Garbage Collection, `destroyTensor` fails to locate the pointer in `alreadyDestroyed` (as it was just cleared @ the prev Garbage Collection run).

It seems like there might be a bug in Bun, working on a [repro](https://github.com/cryptodeal/GC_Bug) to file an issue w Bun as this is likely blocking.

Once we resolve the above, this will partially implement #50 (still want to implement some equivalent to TFJS `tidy` in a separate PR).

### CODE REVIEW

**Comment by cryptodeal** [comment]
S/o @jacobkahn & @bwasti for getting `releaseAdapterUnsafe` merged into Flashlight quickly! Tests are passing, but we'll still need to handle preventing the reuse of a tensor after `dispose` has been called on it.

The simplest solution is to add `is_disposed` boolean value to Tensor class, which we flag after `dispose` has been called; we'd need to then do the following in any Tensor Operation/class method that would throw an error:

```ts
if (this.is_disposed) throw new Error(`cannot call "op_name" on disposed tensor; ${this.toString})
```

I tested and this approach seems to work locally; however obviously it requires hardcoding checks/throwing, so would love feedback to see if we can't brainstorm a smarter approach to handling this!

**Comment by asilvas** [comment]
@cryptodeal any harm in just letting Flashlight throw to avoid the extra check? Or is it seg faulting?

**Comment by cryptodeal** [comment]
> @cryptodeal any harm in just letting Flashlight throw to avoid the extra check? Or is it seg faulting?

I wish, that would be convenient, but it Segfaults unfortunately.

**Comment by cryptodeal** [comment]
Here's what I think a utility function intended to handle throwing this error might look like:

```ts
export const _handle_disposed = (t: Tensor | Tensor[]) => {
  if (Array.isArray(t)) {
    const test = t.filter(tensor => tensor.is_disposed)
    if (test.length) {
      throw new Error(`Cannot operate on previously disposed Tensor(s): ${test.map(t => t.toString()).join(', ')}`)
    }
  } else {
    if (t.is_disposed) throw new Error(`Cannot operate on previously disposed Tensor: ${t.toString()}`)
  }
}
```

This could be easily added as a check at the start of all relevant JS methods (and easily added to the programmatically generated JS code w/ minimal added work to maintain going forward.

**Review by bwasti — APPROVED** [review]
awesome!  I don't think this needs feedback anymore :)

going to punt on the throw vs segfault issue.  Right now I think we can say this is a bit dangerous to use - `tidy` will help a lot

**Pull request merged**
