### PR TITLE
Add More Tests

### PR DESCRIPTION
**Pull request by cryptodeal**
### Supported Operations Tests
- [ ] rand
- [ ] randn
- [ ] full
- [ ] identity
- [ ] arange
- [ ] iota
- [x] reshape
- [x] transpose
- [x] tile
- [ ] nonzero
- [x] negative
- [ ] logicalNot
- [x] exp
- [x] log
- [ ] log1p
- [x] sin
- [x] cos
- [ ] sqrt
- [ ] tanh
- [x] floor
- [x] ceil
- [ ] rint
- [ ] absolute
- [x] abs
- [x] sigmoid
- [x] erf
- [x] flip (1D Tensor; addtl tests after 100% coverage basic ops)
- [ ] clip
- [ ] roll
- [x] isnan
- [x] isinf
- [x] sign
- [ ] tril
- [ ] triu
- [ ] where
- [ ] sort
- [x] add
- [x] sub
- [x] mul
- [x] div
- [ ] eq
- [ ] neq
- [ ] lessThan
- [ ] lessThanEqual
- [ ] greaterThan
- [ ] greaterThanEqual
- [ ] logicalOr
- [ ] logicalAnd
- [ ] mod
- [ ] bitwiseAnd
- [ ] bitwiseOr
- [ ] bitwiseXor
- [ ] lShift
- [ ] rShift
- [x] minimum
- [x] maximum
- [ ] power
- [ ] matmul
- [ ] amin
- [ ] amax
- [ ] argmin
- [ ] argmax
- [x] sum
- [ ] cumsum
- [x] mean
- [ ] median
- [ ] var
- [ ] std
- [x] norm
- [ ] countNonzero
- [ ] any
- [ ] all

### Tensor Class Methods & Properties Tests
- [ ] backward
- [ ] ndim
- [x] shape (used in tests)
- [ ] toString
- [ ] valueOf (used in tests)
- [ ] asContiguousTensor
- [x] copy
- [ ] detach
- [x] elements (used in tests)
- [x] toFloat32Array (tested implicitly in `valueOf`)
- [x] toFloat32 (tested implicitly in `valueOf`)

### CODE REVIEW

**Comment by cryptodeal** [comment]
Added tests for erf, isinf, isnan, sigmoid, and flip (only 1D Tensors though, so will need to add additional tests once completed basic coverage of all operations).

**Review by bwasti — APPROVED** [review]
thanks!

**Comment by jacobkahn** [comment]
@cryptodeal if you rebase know master, you should now get a CI signal for all this across platforms!

**Comment by cryptodeal** [comment]
Interesting, one of the tests for isinf fails normally (I know Infinity isn't supported yet), but it's only throwing a C++ Exception when running tests using CUDA Backend.

**Comment by cryptodeal** [comment]
Interestingly, flip on 1D tensor seems to only pass sometimes. I've run it locally a bunch and it alternates between pass fail (passed in the CI above on macOS)

**Pull request merged**
